"""Generate proposed deployable_setups.yml rows for AI-thematic variants
that cleared the deployment gate in the sweep.

Reads the sweep summary at ``journal/backtest-sweep/2026-05-29-ai-thematic.md``
(or the path passed via --report), parses the per-variant verdict +
headline metrics from the summary table, and emits YAML row text the user
hand-pastes into ``tools/deployable_setups.yml``.

The same edit MUST also backfill ``track: generic`` on the existing 6
deployable rows (Alfred Delta 4) — that part is a manual edit, not
generated by this script.

Does NOT auto-write.

Usage::

    uv run python scripts/promote_ai_thematic_setups.py
    uv run python scripts/promote_ai_thematic_setups.py --report path/to/sweep.md
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


DEFAULT_REPORT = Path("journal/backtest-sweep/2026-05-29-ai-thematic.md")

# variant → (kind, universe_name) for row composition. Mirrors the VARIANTS
# table in scripts/backtest_sweep_ai_thematic.py but is the minimum needed
# to construct deployable rows.
VARIANT_META: dict[str, tuple[str, str]] = {
    "xs_short_term_reversal_ai_pure": (
        "xs_short_term_reversal",
        "ai_thematic_pure_2026q2 (41-ticker AI pure-play)",
    ),
    "xs_short_term_reversal_ai_broad": (
        "xs_short_term_reversal",
        "ai_thematic_broad_2026q2 (~132-ticker AI runoff/gushers)",
    ),
    "connors_rsi2_ai_pure": (
        "connors_rsi2",
        "ai_thematic_pure_2026q2 (41-ticker AI pure-play)",
    ),
    "connors_rsi2_ai_broad": (
        "connors_rsi2",
        "ai_thematic_broad_2026q2 (~132-ticker AI runoff/gushers)",
    ),
    "clenow_momentum_ai_broad": (
        "clenow_momentum",
        "ai_thematic_broad_2026q2 (~132-ticker AI runoff/gushers)",
    ),
}


def parse_summary_table(report_md: str) -> list[dict]:
    """Parse the | Variant | Profile | Sharpe | ... | Verdict | summary table.

    Tolerates the sweep writer's literal ``|MDD|`` header by collapsing
    that bare-pipe span back to ``MDD%`` before splitting cells.
    """
    rows: list[dict] = []
    in_table = False
    headers: list[str] = []
    for raw in report_md.splitlines():
        line = raw.replace("| |MDD| |", "| MDD% |")
        if line.startswith("| Variant "):
            headers = [c.strip() for c in line.strip("|").split("|")]
            in_table = True
            continue
        if in_table and line.startswith("|---"):
            continue
        if in_table:
            if not line.startswith("|"):
                in_table = False
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) != len(headers):
                continue
            row = dict(zip(headers, cells))
            rows.append(row)
    return rows


def _strip_md_bold(s: str) -> str:
    return re.sub(r"\*\*([^*]+)\*\*", r"\1", s).strip()


def _row_verdict(row: dict) -> str:
    v = _strip_md_bold(row.get("Verdict", ""))
    return v.upper()


def render_row(row: dict, today: date) -> str:
    """Render a proposed deployable_setups.yml row from a sweep table row."""
    variant = row["Variant"]
    profile = row["Profile"]
    sharpe = row["Sharpe"]
    mdd_cell = row.get("MDD%", row.get("|MDD|", "0"))
    mdd = mdd_cell.rstrip("%")
    n = row["n"]
    per_window = row["Per-window"]  # e.g. "5/6"
    top_k_frac = row.get("Top-3 Contrib", "—")
    kind, universe_desc = VARIANT_META.get(variant, (variant, "(unknown universe)"))
    top_k_note = (
        f" Top-3-ticker contribution to OOS |PnL|: {top_k_frac}. "
        if top_k_frac and top_k_frac != "—"
        else ""
    )
    is_pure = profile == "ai_thematic_pure"
    half_size = (
        " **DEPLOY HALF-SIZE** first month (universe-narrowness "
        "concentration prudence — first ai_thematic_pure-profile deploy)."
        if is_pure else ""
    )
    return (
        f"  - setup: {variant}\n"
        f"    variant: \"AI-thematic clone of {kind} ({profile} gate profile)\"\n"
        f"    universe: \"{universe_desc}\"\n"
        f"    backtest_window: \"2017-01-01..2026-05-25 (6 OOS years)\"\n"
        f"    rolling_agg_sharpe: {sharpe}\n"
        f"    rolling_agg_max_dd_pct: -{mdd}\n"
        f"    n: {n}\n"
        f"    per_window_pass_rate: \"{per_window}\"\n"
        f"    cleared_at: {today.isoformat()}\n"
        f"    cleared_under_gate_profile: {profile}\n"
        f"    track: ai_thematic\n"
        f"    notes: \"AI-thematic auto-paper track (Alfred-refined plan, "
        f"see plans/polymorphic-tickling-avalanche.md). Cloned algorithmically-"
        f"identical from the {kind} kind; only universe + (where applicable) "
        f"top_k/bottom_n params differ from the generic deployable. Gate "
        f"profile {profile} per Alfred Delta 1.{top_k_note}{half_size} "
        f"Full report: journal/backtest/{variant}-ai-thematic.md.\"\n"
    )


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--report", default=str(DEFAULT_REPORT))
    args = p.parse_args()

    report_path = Path(args.report)
    if not report_path.is_file():
        sys.exit(f"# report not found: {report_path}")
    report_md = report_path.read_text(encoding="utf-8")
    rows = parse_summary_table(report_md)
    if not rows:
        sys.exit(f"# no summary table parsed from {report_path}")
    today = date.today()

    deploy_rows = [r for r in rows if _row_verdict(r) == "DEPLOY"]
    review_rows = [r for r in rows if _row_verdict(r) == "REVIEW"]
    reject_rows = [r for r in rows if _row_verdict(r) == "REJECT"]

    out: list[str] = []
    out.append("# ============================================================")
    out.append("# AI-thematic deployable rows — hand-paste under `deployable:`")
    out.append("# in tools/deployable_setups.yml.")
    out.append("#")
    out.append("# REMINDER (Alfred Delta 4): in the SAME edit, backfill")
    out.append("# `track: generic` on the existing 6 deployable rows so the")
    out.append("# track: field is set everywhere (no absence-as-default).")
    out.append("# ============================================================")
    out.append("")
    if not deploy_rows and not review_rows:
        out.append("# (no variants cleared the gate — nothing to paste)")
    else:
        for r in deploy_rows + review_rows:
            out.append(render_row(r, today))
    out.append("# ----- summary -----")
    out.append(f"# DEPLOY rows above: {len(deploy_rows)}")
    out.append(f"# REVIEW rows above: {len(review_rows)} "
               "(gate-pass + top-3 flagged — manual decision)")
    out.append(f"# REJECT (not pasted): {len(reject_rows)}")
    for r in reject_rows:
        mdd_cell = r.get("MDD%", r.get("|MDD|", "?"))
        out.append(f"#   - {r['Variant']} (Sharpe {r['Sharpe']} / "
                   f"|MDD| {mdd_cell} / clauses "
                   f"{r['Clause-1']}/{r['Clause-2']})")
    print("\n".join(out))


if __name__ == "__main__":
    main()
